[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "4dXV628acNZ79ttyxwUYEMy7WKZj7K2oQ6j1RBBPb4az"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/vijay/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
